### ISSUE TITLE
Doesn't correctly score 'double-win'

### ISSUE THREAD

**Issue by jpmartin2** [chaitu236/TakServer#14]
When a move creates roads for both players at once, the current rules dictate that the active player wins. However, currently, it seems to be scored as a tie.

**Comment by chaitu236** [comment]
Ah yes this was changed in latest rules. Thanks for bringing to my notice.

**Comment by chaitu236** [comment]
Fixed in 582cb691327678f08c8be900073dfdafe2d06dc0
