### ISSUE TITLE
Database IDs should match online IDs

### ISSUE THREAD

**Issue by nelhage** [chaitu236/TakServer#18]
Right now, the IDs received via the server protocol are not the same IDs that end up in the database. A lot of things would be more convenient, programmatically, if they did – for example, a tool could automatically generate archive links from games in real-time. It would enable me to cross-reference my own logs with the server database.

**Comment by chaitu236** [comment]
This is because when saving games to db, I don't specify the game id and let the db pick the next one. If I use the game id as db id, when server is restarted there will be unused db ids since games ongoing during restart are not committed to db. I'll have to think about this a little.

**Comment by nelhage** [comment]
I think -- without having read too much of the code -- that the natural thing here would be to insert "placeholder" games as soon as the game starts, and use the returned id, and then update the record on completion.

**Comment by chaitu236** [comment]
But when server is restarted, the placeholder games can't be populated as they're not completed..

**Comment by chaitu236** [comment]
I should just record those games as aborted.. yes I'll do that I think
