### ISSUE TITLE
Registration and Password reset emails, not arriving

### ISSUE THREAD

**Issue by nicwest** [chaitu236/TakServer#21]
Hey Team, probably not the best place for this, but I can't see another contact on the site.

I have just attempted to register, but have yet to receive an email confirmation. I attempted a password reset with the same result.

here is what I did:
1. go to http://www.playtak.com
2. logged in as guest
3. played one game against the beginner bot (won!)
4. played one game against the intermediate bot (won!)
5. attempted to register (boshlol:[my email]@gmail.com)
6. see the check your email message.
7. no email
8. message says disconnected from play tak
9 . refresh the page
10. reset password
11. "token sent to your email"
12. no email
13. message says disconnected from server.

**Comment by chaitu236** [comment]
Hey.. thanks for letting me know. There was an issue with the mail server. I put a temporary fix for now so go ahead and reset your password.

**Comment by nicwest** [comment]
That seems to have done the trick, thanks buddy. will go ahead and close this.
