### ISSUE TITLE
Getting NOK from Ping

### ISSUE THREAD

**Issue by scottven** [chaitu236/TakServer#7]
TakBot was getting disconnected after a couple minutes of idle time, so I figured the server had started checking pings.  I enabled TakBot to send a Ping every 30 seconds and the server always returns "NOK".

**Comment by scottven** [comment]
Looks like it's a documentation issue.  The doc says "Ping" but the code looks for "PING".  I updated TakBot to send PING and now the server returns "OK".

**Comment by chaitu236** [comment]
Fixed the documentation.
